-- biz_spot full CREATE (base columns + Wave-2 bilingual columns)
-- Source: Spot.java in this repo. Skip wave2_biz_spot_bilingual_ddl.sql after this file.
-- MySQL 8 / utf8mb4

CREATE TABLE IF NOT EXISTS `biz_spot` (
  `id` varchar(64) NOT NULL COMMENT '主键',
  `slug` varchar(64) DEFAULT NULL COMMENT 'scenic business key',
  `spot_name` varchar(255) DEFAULT NULL COMMENT '景区名称',
  `spot_name_en` varchar(255) DEFAULT NULL COMMENT 'English name',
  `longitude` double DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `address` varchar(512) DEFAULT NULL,
  `city` varchar(128) DEFAULT NULL,
  `city_en` varchar(128) DEFAULT NULL,
  `opening_time` varchar(512) DEFAULT NULL,
  `opening_time_en` varchar(512) DEFAULT NULL,
  `description` text,
  `description_en` text,
  `summary` text,
  `summary_en` text,
  `spot_tags` json DEFAULT NULL,
  `is_prebook` varchar(32) DEFAULT NULL,
  `website_url` varchar(512) DEFAULT NULL,
  `contact_phone` varchar(64) DEFAULT NULL,
  `cover` json DEFAULT NULL,
  `images` json DEFAULT NULL,
  `video` json DEFAULT NULL,
  `rate` decimal(10,2) DEFAULT NULL,
  `plat` json DEFAULT NULL,
  `start_level` int DEFAULT NULL,
  `level_label` text COMMENT '等级标签 JSON 或短文案',
  `traffice` text,
  `traffice_en` text,
  `ticket_summary` text,
  `ticket_summary_en` text,
  `visit_tips` text,
  `visit_tips_en` text,
  `best_season` text,
  `best_season_en` text,
  `comment_num` int DEFAULT NULL,
  `ext_json` longtext,
  `bilingual_json` longtext,
  `delete_flag` varchar(32) DEFAULT 'NOT_DELETE',
  `create_time` datetime DEFAULT NULL,
  `create_user` varchar(64) DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `update_user` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_biz_spot_slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='景区表（含双语列）';
